// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa_xmFms8EWF8GHCKsZBq8uOS73WQ4zaA',
    appId: '1:1065200420625:web:518a296dfacfef4375aeb0',
    messagingSenderId: '1065200420625',
    projectId: 'mental-health-504cf',
    authDomain: 'mental-health-504cf.firebaseapp.com',
    storageBucket: 'mental-health-504cf.appspot.com',
    measurementId: 'G-6RTSFPENQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAygUUhzX_MYSM-pVhoFaFjYVd3Svozg6Q',
    appId: '1:1065200420625:android:10d3701358b0800775aeb0',
    messagingSenderId: '1065200420625',
    projectId: 'mental-health-504cf',
    storageBucket: 'mental-health-504cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOJg01xtj-c-wgrbU-MgFaUpoQy2Th4bY',
    appId: '1:1065200420625:ios:eec27c5f6eb9d31875aeb0',
    messagingSenderId: '1065200420625',
    projectId: 'mental-health-504cf',
    storageBucket: 'mental-health-504cf.appspot.com',
    iosClientId:
        '1065200420625-gjolr336t9vg7q6hqtsm9s4b4v77lec3.apps.googleusercontent.com',
    iosBundleId: 'com.example.riesgoSuicida',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOJg01xtj-c-wgrbU-MgFaUpoQy2Th4bY',
    appId: '1:1065200420625:ios:eec27c5f6eb9d31875aeb0',
    messagingSenderId: '1065200420625',
    projectId: 'mental-health-504cf',
    storageBucket: 'mental-health-504cf.appspot.com',
    iosClientId:
        '1065200420625-gjolr336t9vg7q6hqtsm9s4b4v77lec3.apps.googleusercontent.com',
    iosBundleId: 'com.example.riesgoSuicida',
  );
}
